In [217]:
import pandas as pd
import numpy as np
import torch
from torch import nn

df = pd.read_csv("./datasets/diabetes_risk_prediction_dataset.csv")
df

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity     class  
0                No              Yes      Yes     Yes  Positive  
1               Yes               No      Yes      No  Positive  
2                No              Yes      Yes      No  Positive  
3                No               No       No      No  Positive  
4               Yes              Yes      Yes     Yes  Positive  
..              ...              ...      ...     ...       ...  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative  

[520 rows x 17 columns]

In [218]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
df[df.select_dtypes(object).columns] = oe.fit_transform(df.select_dtypes(object))
df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     40     1.0       0.0         1.0                 0.0       1.0   
1     58     1.0       0.0         0.0                 0.0       1.0   
2     41     1.0       1.0         0.0                 0.0       1.0   
3     45     1.0       0.0         0.0                 1.0       1.0   
4     60     1.0       1.0         1.0                 1.0       1.0   
..   ...     ...       ...         ...                 ...       ...   
515   39     0.0       1.0         1.0                 1.0       0.0   
516   48     0.0       1.0         1.0                 1.0       1.0   
517   58     0.0       1.0         1.0                 1.0       1.0   
518   32     0.0       0.0         0.0                 0.0       1.0   
519   42     1.0       0.0         0.0                 0.0       0.0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0.0             0.0              0.0      1.0           0.0   
1           0.0             0.0              1.0      0.0           0.0   
2           1.0             0.0              0.0      1.0           0.0   
3           1.0             1.0              0.0      1.0           0.0   
4           1.0             0.0              1.0      1.0           1.0   
..          ...             ...              ...      ...           ...   
515         1.0             0.0              0.0      1.0           0.0   
516         1.0             0.0              0.0      1.0           1.0   
517         1.0             0.0              1.0      0.0           0.0   
518         0.0             0.0              1.0      1.0           0.0   
519         0.0             0.0              0.0      0.0           0.0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1.0              0.0               1.0       1.0      1.0   
1                0.0              1.0               0.0       1.0      0.0   
2                1.0              0.0               1.0       1.0      0.0   
3                1.0              0.0               0.0       0.0      0.0   
4                1.0              1.0               1.0       1.0      1.0   
..               ...              ...               ...       ...      ...   
515              1.0              1.0               0.0       0.0      0.0   
516              1.0              1.0               0.0       0.0      0.0   
517              0.0              1.0               1.0       0.0      1.0   
518              1.0              0.0               0.0       1.0      0.0   
519              0.0              0.0               0.0       0.0      0.0   

     class  
0      1.0  
1      1.0  
2      1.0  
3      1.0  
4      1.0  
..     ...  
515    1.0  
516    1.0  
517    1.0  
518    0.0  
519    0.0  

[520 rows x 17 columns]

In [219]:
from sklearn.model_selection import train_test_split

X = torch.tensor(df.drop(columns=['class']).values).to(torch.float32)
y = torch.tensor(df['class'].values).to(torch.float32)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [221]:

from sklearn.linear_model import LogisticRegression


class Logistic(nn.Module):
    def __init__(self):
        super(Logistic,self).__init__()
        self.fc1 = nn.Linear(16, 16)
        self.tahn = nn.Tanh()
        self.fc2 = nn.Linear(16,1)
        self.sigm = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = self.tahn(x)
        x = self.fc2(x)
        x = self.sigm(x)
        return x

model = Logistic()
optim = torch.optim.Adam(model.parameters(),lr=0.001)
loss_func = nn.BCELoss()

In [222]:
model(X_train)

tensor([[0.5756],
        [0.5683],
        [0.5734],
        [0.5732],
        [0.5720],
        [0.5730],
        [0.5719],
        [0.5746],
        [0.5719],
        [0.5734],
        [0.5720],
        [0.5757],
        [0.5751],
        [0.5734],
        [0.5733],
        [0.5717],
        [0.5790],
        [0.5736],
        [0.5722],
        [0.5771],
        [0.5745],
        [0.5722],
        [0.5740],
        [0.5711],
        [0.5735],
        [0.5738],
        [0.5735],
        [0.5723],
        [0.5731],
        [0.5736],
        [0.5719],
        [0.5722],
        [0.5738],
        [0.5749],
        [0.5720],
        [0.5734],
        [0.5743],
        [0.5720],
        [0.5732],
        [0.5722],
        [0.5683],
        [0.5718],
        [0.5733],
        [0.5735],
        [0.5736],
        [0.5720],
        [0.5729],
        [0.5744],
        [0.5732],
        [0.5711],
        [0.5739],
        [0.5731],
        [0.5720],
        [0.5754],
        [0.5724],
        [0

In [223]:
from sklearn.metrics import classification_report

sk_model = LogisticRegression(max_iter=1000)
sk_model.fit(X_train, y_train)
y_preds = sk_model.predict(X_test)
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

         0.0       0.90      0.85      0.88        33
         1.0       0.93      0.96      0.94        71

    accuracy                           0.92       104
   macro avg       0.92      0.90      0.91       104
weighted avg       0.92      0.92      0.92       104


In [224]:
from sklearn.metrics import roc_auc_score
for epoch in range(1000):
    optim.zero_grad()
    #print(loss_func(y_train,model(X_train).reshape(-1)))
    loss = loss_func(model(X_train).reshape(-1),y_train)
    loss.backward()
    optim.step()

In [226]:
model(X_train)

tensor([[0.9987],
        [0.9997],
        [0.2679],
        [0.2174],
        [0.0185],
        [0.1083],
        [0.0185],
        [0.9996],
        [0.1430],
        [0.2679],
        [0.0901],
        [0.9896],
        [0.0375],
        [0.0570],
        [0.7740],
        [0.0391],
        [0.9997],
        [0.6873],
        [0.9989],
        [0.9996],
        [0.9887],
        [0.9969],
        [0.9989],
        [0.0192],
        [0.9989],
        [0.0187],
        [0.9996],
        [0.9453],
        [0.9995],
        [0.9967],
        [0.1430],
        [0.7850],
        [0.9989],
        [0.9958],
        [0.0233],
        [0.9952],
        [0.1927],
        [0.0185],
        [0.9976],
        [0.9989],
        [0.9997],
        [0.9801],
        [0.9716],
        [0.0106],
        [0.9171],
        [0.9656],
        [0.2560],
        [0.9944],
        [0.9219],
        [0.0192],
        [0.9988],
        [0.0105],
        [0.0590],
        [0.9990],
        [0.0748],
        [0

In [227]:
y_train

tensor([1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
        1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
        0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
        0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
        0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
        1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
        0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
        1., 1., 0., 1., 0., 1., 0., 1., 

In [228]:
model(X_train).reshape(-1)

tensor([0.9987, 0.9997, 0.2679, 0.2174, 0.0185, 0.1083, 0.0185, 0.9996, 0.1430,
        0.2679, 0.0901, 0.9896, 0.0375, 0.0570, 0.7740, 0.0391, 0.9997, 0.6873,
        0.9989, 0.9996, 0.9887, 0.9969, 0.9989, 0.0192, 0.9989, 0.0187, 0.9996,
        0.9453, 0.9995, 0.9967, 0.1430, 0.7850, 0.9989, 0.9958, 0.0233, 0.9952,
        0.1927, 0.0185, 0.9976, 0.9989, 0.9997, 0.9801, 0.9716, 0.0106, 0.9171,
        0.9656, 0.2560, 0.9944, 0.9219, 0.0192, 0.9988, 0.0105, 0.0590, 0.9990,
        0.0748, 0.1016, 0.9478, 0.0106, 0.9219, 0.0185, 0.6764, 0.9998, 0.7740,
        0.1980, 0.9936, 0.9988, 0.1438, 0.2579, 0.0748, 0.9914, 0.9956, 0.5208,
        0.0294, 0.0129, 0.9987, 0.0308, 0.0187, 0.6873, 0.9979, 0.9993, 0.1016,
        0.9954, 0.9877, 0.9991, 0.2174, 0.9992, 0.9968, 0.9991, 0.9962, 0.0192,
        0.0129, 0.9977, 0.9106, 0.9943, 0.2174, 0.0306, 0.9993, 0.0091, 0.0192,
        0.9980, 0.0294, 0.9914, 0.0577, 0.1354, 0.9919, 0.0172, 0.1430, 0.0827,
        0.8748, 0.9288, 0.9999, 0.9991, 

In [229]:
y_preds = model.forward(X_test)
print(classification_report(y_test,np.round(y_preds.detach().numpy())))

              precision    recall  f1-score   support

         0.0       0.94      0.91      0.92        33
         1.0       0.96      0.97      0.97        71

    accuracy                           0.95       104
   macro avg       0.95      0.94      0.94       104
weighted avg       0.95      0.95      0.95       104
